services:
  db:
    image: mysql:8.0
    container_name: biblioteca_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123Biblioteca 
      MYSQL_DATABASE: biblioteca_db           
      MYSQL_USER: api_user                    
      MYSQL_PASSWORD: apisenha1230    
    
    
    command: --default-authentication-plugin=mysql_native_password
    
    ports:
      - "3306:3306"
      
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: {}